-- phpMyAdmin SQL Dump
-- version 3.3.8.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 23, 2012 at 11:36 PM
-- Server version: 5.5.8
-- PHP Version: 5.3.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `culturecode`
--

-- --------------------------------------------------------

--
-- Table structure for table `ncl_plaques`
--

CREATE TABLE IF NOT EXISTS `ncl_plaques` (
  `uid` int(3) DEFAULT NULL,
  `trail_point` int(2) DEFAULT NULL,
  `title` varchar(56) DEFAULT NULL,
  `short_text` varchar(380) DEFAULT NULL,
  `full_text` varchar(380) DEFAULT NULL,
  `video_embed_url` varchar(15) DEFAULT NULL,
  `audio` varchar(22) DEFAULT NULL,
  `lat` decimal(8,6) DEFAULT NULL,
  `lng` decimal(8,6) DEFAULT NULL,
  `zoom` int(2) DEFAULT NULL,
  `image` varchar(80) DEFAULT NULL,
  `full_link` varchar(10) DEFAULT NULL,
  `trail` int(1) DEFAULT NULL,
  `pointtype` varchar(4) DEFAULT NULL,
  `divposition` varchar(10) DEFAULT NULL,
  `divleft` varchar(10) DEFAULT NULL,
  `divright` varchar(10) DEFAULT NULL,
  `divxindex` varchar(10) DEFAULT NULL,
  `postop` varchar(10) DEFAULT NULL,
  `posleft` varchar(10) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ncl_plaques`
--

INSERT INTO `ncl_plaques` (`uid`, `trail_point`, `title`, `short_text`, `full_text`, `video_embed_url`, `audio`, `lat`, `lng`, `zoom`, `image`, `full_link`, `trail`, `pointtype`, `divposition`, `divleft`, `divright`, `divxindex`, `postop`, `posleft`) VALUES
(66, 1, 'High Level Bridge', '<p>	<strong>High Level Bridge</strong></p><p>	The original lighting columns on the High Level Bridge were refurnished and brought back into service by Network Rail in 2008, with funding contributions from: The Railway Heritage Trust Gateshead Metropolitan Borough Council Newcastle City Council&nbsp;<br />	&nbsp;</p>', '<p>	The original lighting columns on the High Level Bridge were refurnished and brought back into service by Network Rail in 2008, with funding contributions from: The Railway Heritage Trust Gateshead Metropolitan Borough Council Newcastle City Council<br />	&nbsp;</p>', NULL, 'barn_owl1331225502.mp3', 54.967010, -1.608628, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3534.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(67, 2, 'The Tyne Bridges...', '<p>	<strong>The Tyne Bridges...</strong></p><p>	1891-1991 Centenary Award for Outstanding Civil Engineering Achievement The Tyne Bridges Landmarks which was become The Symbols of Tyneside<br />	&nbsp;</p>', '<p>	1891-1991 Centenary Award for Outstanding Civil Engineering Achievement The Tyne Bridges Landmarks which was become The Symbols of Tyneside<br />	&nbsp;</p>', 'serydrty tyhftu', 'barn_owl1331226632.mp3', 54.967995, -1.608317, 16, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3628.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(68, 3, 'The Tyne Bridge 75th Aniversary...', '<p>	<strong>Tyne Bridge 75th Anniversary...</strong></p><p>	Designed by Mott, Hay &amp; Anderson. Constructed by Dorman Long &amp; Co. Opened 10th October 1928 by HM King George V accompanied by HM Queen Mary<br />	&nbsp;</p>', '<p>	Tyne Bridge 75th Anniversary Designed by Mott, Hay &amp; Anderson. Constructed by Dorman Long &amp; Co. Opened 10th October 1928 by HM King George V accompanied by HM Queen Mary<br />	&nbsp;</p>', NULL, 'barn_owl1331228648.mp3', 54.968437, -1.606686, 16, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3627.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(69, 4, 'Admiral Lord Collingwood...', '<p>	<strong>Admiral Lord Collingwood 1748-1810 ...</strong></p><p>	Victor of Trafalgar, diplomat, wit and humanitarian. Nelson&#39;s friend and comrade. Born in a house on this site. &quot;Since heaven made gentlemen there is no recordof a better one&quot;- (W.M.Thackeray).<br />	&nbsp;</p>', '<p>	Admiral Lord Collingwood 1748-1810 Victor of Trafalgar, diplomat, wit and humanitarian. Nelson&#39;s friend and comrade. Born in a house on this site. &quot;Since heaven made gentlemen there is no recordof a better one&quot;- (W.M.Thackeray).<br />	&nbsp;</p>', NULL, 'barn_owl1331229074.mp3', 54.969559, -1.611010, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3613.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(70, 5, 'Cardinal Basil Hume', '<p>	<strong>Cardinal Basil Hume 1923-1999 </strong></p><p>	Spiritual Leader Born here on 2 March<br />	&nbsp;</p>', '<p>	Cardinal Basil Hume 1923-1999 Spiritual Leader Born here on 2 March<br />	&nbsp;</p>', NULL, NULL, 54.976437, -1.607405, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3553.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(71, 6, 'Charles Avision', '<p>	<strong>Charles Avison 1709-1770 </strong></p><p>	Composer Held his first public subscription concert in this building in 1735. The first assembly Rooms in Newcastle 1716-173c6<br />	&nbsp;</p>', '<p>	Charles Avison 1709-1770 Composer Held his first public subscription concert in this building in 1735. The first assembly Rooms in Newcastle 1716-173c6<br />	&nbsp;</p>', NULL, NULL, 54.970016, -1.615999, 16, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3580.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(72, 7, 'Charles Avison', '<p>	<strong>Charles Avison 1709-1770 Composer </strong></p><p>	The foremost English concerto composer of the 18th century; lived and worked in a house in Rosemary Lane in the 1730s when he was appointed Organist to St. John&#39;s and St Nicholas Churches.<br />	&nbsp;</p>', '<p>	Charles Avison 1709-1770 Composer The foremost English concerto composer of the 18th century; lived and worked in a house in Rosemary Lane in the 1730s when he was appointed Organist to St. John&#39;s and St Nicholas Churches.<br />	&nbsp;</p>', NULL, NULL, 54.969929, -1.615173, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3582.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(73, 8, 'Charles Avison', '<p>	<strong>Charles Avison 1709-1770 </strong></p><p>	The foremost English concerto composer of the 18th century: organist, writer on music, and concert director. He was born and worked in Newcastle. Buried here by the Nave Porch.<br />	&nbsp;</p>', '<p>	Charles Avison 1709-1770 The foremost English concerto composer of the 18th century: organist, writer on music, and concert director. He was born and worked in Newcastle. Buried here by the Nave Porch.<br />	<br />	&nbsp;</p>', NULL, NULL, 54.973427, -1.617769, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3516.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(74, 9, 'Charles Dickens', '<p>	<strong>Charles Dickens 1812-1870</strong></p><p>	Charles Dickens gave public readings of his works in this theatre during 6 visits to Newcastle between 1852 and 1867<br />	&nbsp;</p>', '<p>	Charles Dickens 1812-1870 Charles Dickens gave public readings of his works in this theatre during 6 visits to Newcastle between 1852 and 1867<br />	&nbsp;</p>', NULL, NULL, 54.973461, -1.614325, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3601.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(75, 10, 'Chas Chandler', '<p>	<strong>Chas Chandler</strong></p><p>	Founder member of the &#39;Animals&#39;, manager of Jimi Hendrix and Slade and co-founder of the Newcastle Arena lived in this house 1938-54.<br />	&nbsp;</p>', '<p>	<strong>Chas Chandler</strong></p><p>	Founder member of the &#39;Animals&#39;, manager of Jimi Hendrix and Slade and co-founder of the Newcastle Arena lived in this house 1938-54.<br />	&nbsp;</p>', NULL, NULL, 54.983494, -1.579027, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3677.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(76, 11, 'Dr. Charles John Gibb', '<p>	<strong>Dr. Charles John Gibb 1824-1916</strong></p><p>	&quot;Some went to the dispensary And some to Doctor Gibb&#39;s&quot; The eminent Newcastle surgeon, celebrated in &quot;The Blaydon Races&quot; lived here from 1861<br />	&nbsp;</p>', '<p>	Dr. Charles John Gibb 1824-1916</p><p>	&quot;Some went to the dispensary And some to Doctor Gibb&#39;s&quot; The eminent Newcastle surgeon, celebrated in &quot;The Blaydon Races&quot; lived here from 1861<br />	&nbsp;</p>', NULL, NULL, 54.970139, -1.617469, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3578.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(77, 12, 'Dr. William Rea', '<p>	<strong>Dr. William Rea 1827-1903 </strong></p><p>	Prominent Victorian musician and Founder of the Newcastle Amateur Vocal Society. Lived here from 1877 until his death in 1903<br />	&nbsp;</p>', '<p>	Dr. William Rea 1827-1903</p><p>	Prominent Victorian musician and Founder of the Newcastle Amateur Vocal Society. Lived here from 1877 until his death in 1903<br />	&nbsp;</p>', NULL, NULL, 54.970009, -1.627328, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3572.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(78, 13, 'Father James Worswick', '<p>	<strong>Father James Worswick 1771-1843 </strong></p><p>	Catholic Priest who founded St. Andrew&#39;s Roman Catholic Church, on this site from 1798-1841. A respected, selfless man who gave forty years of loyal service to the city and people.<br />	&nbsp;</p>', '<p>	Father James Worswick 1771-1843</p><p>	Catholic Priest who founded St. Andrew&#39;s Roman Catholic Church, on this site from 1798-1841. A respected, selfless man who gave forty years of loyal service to the city and people.<br />	&nbsp;</p>', NULL, NULL, 54.973003, -1.609733, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3599.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(79, 14, 'Gladstone Adams', '<p>	<strong>Gladstone Adams 1880-1966 </strong></p><p>	Inventor and Photographer Invented the car windscreen wiper in 1911 He was born 16 May 1880 at 4. St Anne&#39;s Row, close to the Ouseburn Mission, which occupied this building from 1869.<br />	&nbsp;</p>', '<p>	Gladstone Adams 1880-1966 Inventor and Photographer Invented the car windscreen wiper in 1911 He was born 16 May 1880 at 4. St Anne&#39;s Row, close to the Ouseburn Mission, which occupied this building from 1869.<br />	&nbsp;</p>', NULL, NULL, 54.972057, -1.599015, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3638.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(80, 15, 'J Alex Burns', '<p>	<strong>J. Alex Burns 1907- 2003 </strong></p><p>	Born in Newcastle. Twice Olympic athlete, AAA 4 mile champion. England cross country team captain and Elswick Harrier. Trained here from 1923 until the early 50s.<br />	&nbsp;</p>', '<p>	J. Alex Burns 1907- 2003</p><p>	Born in Newcastle. Twice Olympic athlete, AAA 4 mile champion. England cross country team captain and Elswick Harrier. Trained here from 1923 until the early 50s.<br />	&nbsp;</p>', NULL, NULL, 54.975777, -1.627307, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3683.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(81, 16, 'Jack Common', '<p>	<strong>Jack Common (Author) 1903-1968 </strong></p><p>	was born here in the upstairs flat. His autobiographical books are &quot;Kiddar&#39;s Luck&quot; (1961) and &quot;The Ampersand&quot; (1964)<br />	&nbsp;</p>', '<p>	Jack Common (Author) 1903-1968</p><p>	was born here in the upstairs flat. His autobiographical books are &quot;Kiddar&#39;s Luck&quot; (1961) and &quot;The Ampersand&quot; (1964)<br />	&nbsp;</p>', NULL, NULL, 54.982082, -1.577450, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3679.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(82, 17, 'John and Albany Hancock', '<p>	<strong>Albany Hancock (1806-1873) &amp; John Hancock (1808-1890) </strong></p><p>	Renowned naturalists, after whom the&nbsp; Hancock Museum was named, lived in this house- formerly 481 Mary&#39;s Terrace 1838-1890<br />	&nbsp;</p>', '<p>	Albany Hancock (1806-1873) &amp; John Hancock (1808-1890)</p><p>	Renowned naturalists, after whom the&nbsp; Hancock Museum was named, lived in this house- formerly 481 Mary&#39;s Terrace 1838-1890<br />	&nbsp;</p>', NULL, NULL, 54.980045, -1.611986, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3586.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(83, 18, 'Jose Maria de Eca de Quiros', '<p>	<strong>Jose Maria de Eca de Quiros 1845-1900 </strong></p><p>	Portuguese diplomant and novelist of European stature lived in this building 1874-1879, among the most productive years of his writing career.<br />	&nbsp;</p>', '<p>	Jose Maria de Eca de Quiros 1845-1900</p><p>	Portuguese diplomant and novelist of European stature lived in this building 1874-1879, among the most productive years of his writing career.<br />	&nbsp;</p>', NULL, NULL, 54.972023, -1.611981, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3509.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(84, 19, 'Lord Armstrong', '<p>	<strong>Lord Armstrong</strong></p><p>	The Banqueting Hall Built in 1860-62 by Sir William (later Lord) Armstrong for entertaining. John Dobson, Architect. Lodge and extensions, 1896-70, by Norman shaw, Architect. Given to Newcastle by Lord Armstrong in 1883.<br />	&nbsp;</p>', '<p>	Lord Armstrong</p><p>	The Banqueting Hall Built in 1860-62 by Sir William (later Lord) Armstrong for entertaining. John Dobson, Architect. Lodge and extensions, 1896-70, by Norman shaw, Architect. Given to Newcastle by Lord Armstrong in 1883.<br />	&nbsp;</p>', NULL, NULL, 54.992832, -1.594654, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3667.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(85, 20, 'Lord Taylor', '<p>	<strong>Peter Murray Taylor, Lord Taylor of Gosforth 1930-1997,</strong></p><p>	Lord Chief Justice of England and Wales. Born 242 Westgate Road. Educated Newcastle Royal Grammar School. His Barristers Chambers were here from 1954-1967<br />	&nbsp;</p>', '<p>	Peter Murray Taylor, Lord Taylor of Gosforth 1930-1997,</p><p>	Lord Chief Justice of England and Wales. Born 242 Westgate Road. Educated Newcastle Royal Grammar School. His Barristers Chambers were here from 1954-1967<br />	&nbsp;</p>', NULL, NULL, 54.969978, -1.617115, 16, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3581.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(86, 21, 'Ludwig Wittgenstein', '<p>	<strong>Ludwig Wittgenstein 1889-1951</strong></p><p>	28 Brandling Park</p><p>	&nbsp;One of the most influential thinkers of the twentieth century lived here in 1945 while working at the Royal Victoria Infirmary<br />	&nbsp;</p>', '<p>	Ludwig Wittgenstein 1889-1951 One of the most influential thinkers of the twentieth century lived here in 1945 while working at the Royal Victoria Infirmary<br />	&nbsp;</p>', NULL, NULL, 54.985279, -1.611055, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/Ludwig_Wittgenstein.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(87, 22, 'Ove Arup', '<p>	<strong>Ove Arup 1895-1958 </strong></p><p>	Engineer and Philosopher. Born here on 16 April<br />	&nbsp;</p>', '<p>	Ove Arup 1895-1958 Engineer and Philosopher. Born here on 16 April<br />	&nbsp;</p>', NULL, NULL, 54.986050, -1.581809, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3675.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(88, 23, 'Ralph Hedley', '<p>	<strong>Ralph Hedley 1848-1913 </strong></p><p>	Renowned Regional Artist, realist Painter, woodcarver and illustrator. Live here from 1885 - 1913<br />	&nbsp;</p>', '<p>	Ralph Hedley 1848-1913 Renowned Regional Artist, realist Painter, woodcarver and illustrator. Live here from 1885 - 1913<br />	&nbsp;</p>', NULL, NULL, 54.983292, -1.629061, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3681.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(89, 24, 'Richard Grainger''s Home', '<p>	<strong>Richard Grainger&#39;s Home</strong></p><p>	36 Clayton Street West Home to Richard Grainger from 1842 to 1861 where he lived with his children and servants</p>', '<p>	36 Clayton Street West Home to Richard Grainger from 1842 to 1861 where he lived with his children and servants</p>', NULL, NULL, 54.969025, -1.620180, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3563.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(90, 25, 'Richard Grainger''s Office', '<p>	<strong>Richard Grainger&#39;s Office</strong></p><p>	28 Clayton Street West Offices of Richard Grainger, visionary and builder. Here on 4th July 1861, he was taken ill while working &amp; died that day</p>', '<p>	28 Clayton Street West Offices of Richard Grainger, visionary and builder. Here on 4th July 1861, he was taken ill while working &amp; died that day</p>', NULL, NULL, 54.969551, -1.619770, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3561.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(91, 26, 'Sid Chaplin', '<p>	<strong>Sid Chaplin 1916-1986 </strong></p><p>	Home of author Sid Chaplin. Formerly a pitman his acclaimed works about the North-East include The Thin Seam and The Day of the Sardine<br />	&nbsp;</p>', '<p>	Sid Chaplin 1916-1986 Home of author Sid Chaplin. Formerly a pitman his acclaimed works about the North-East include The Thin Seam and The Day of the Sardine<br />	&nbsp;</p>', NULL, NULL, 54.987659, -1.590958, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3663.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(92, 27, 'Sir. Joseph Swan', '<p>	<strong>Sir Joseph Swan 1828-1914</strong></p><p>	The inventor of the incandescent light bulb joined John Mawson&#39;s chemist and druggist firm at 13, Mosley Street, in 1846. His experiments here led to important improvements in photographic processing.<br />	&nbsp;</p>', '<p>	Sir Joseph Swan 1828-1914 The inventor of the incandescent light bulb joined John Mawson&#39;s chemist and druggist firm at 13, Mosley Street, in 1846. His experiments here led to important improvements in photographic processing.<br />	&nbsp;</p>', NULL, NULL, 54.970764, -1.610935, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3539.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(93, 28, 'Thomas Bewick', '<p>	<strong>Thomas Bewick 1753-1828 </strong></p><p>	The artist, wood-engraver and naturalist, lived near here in his &#39;little happycot at the Forth&#39; from 1781 to 1812<br />	&nbsp;</p>', '<p>	Thomas Bewick 1753-1828 The artist, wood-engraver and naturalist, lived near here in his &#39;little happycot at the Forth&#39; from 1781 to 1812<br />	&nbsp;</p>', NULL, NULL, 54.969334, -1.618666, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3525.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(94, 29, 'Thomas Bewick''s Workshop', '<p>	<strong>Thomas Bewick 1753-1828</strong></p><p>	The artist and naturalist, celebrated for his &quot;History of British Birds&quot; traded as an engraver and copperplate printer in a workshop on this site from about 1790<br />	&nbsp;</p>', '<p>	Thomas Bewick 1753-1828 The artist and naturalist, celebrated for his &quot;History&nbsp;of&nbsp;British Birds&quot; traded as an engraver and copperplate printer in a workshop on this site from about 1790<br />	&nbsp;</p>', NULL, NULL, 54.970119, -1.610192, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3537.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(95, 30, 'Thomas Burt', '<p>	<strong>Thomas Burt 1837-1922 </strong></p><p>	Northumberland Miners&#39; leader 1865-1913, M.P. for Morpeth 1874-1918, the first working class M.P, lived in this house from 1892 to his death<br />	20 Burdon Terrace, Jesmond<br />	&nbsp;</p>', '<p>	Thomas Burt 1837-1922 Northumberland Miners&#39; leader 1865-1913, M.P. for Morpeth 1874-1918, the first working class M.P, lived in this house from 1892 to his death</p><p>	20 Burdon Terrace, Jesmond<br />	<br />	&nbsp;</p>', NULL, NULL, 54.986210, -1.610232, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3654.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(96, 31, 'William Bell Scott', '<p>	<strong>William Bell Scott 1811-1890 </strong></p><p>	Leading Poet and Pre-Raphaelite painter. Head of Newcastle School of Design. Lived in Newcastle for twenty years and in this house from 1859-1864<br />	14 St. Thomas Crescent<br />	&nbsp;</p>', '<p>	William Bell Scott 1811-1890 Leading Poet and Pre-Raphaelite painter. Head of Newcastle School of Design. Lived in Newcastle for twenty years and in this house from 1859-1864</p><p>	14 St. Thomas Crescent<br />	<br />	&nbsp;</p>', NULL, NULL, 54.976910, -1.617544, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3557.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(97, 32, 'William Hedley', '<p>	<strong>William Hedley 1779-1843 </strong></p><p>	Pioneering locomotive and mining engineer, was baptised here in 1779, married Frances Dodds here in 1803, and is buried in the churchyard.<br />	&nbsp;</p>', '<p>	William Hedley 1779-1843 Pioneering locomotive and mining engineer, was baptised here in 1779, married Frances Dodds here in 1803, and is buried in the churchyard.<br />	&nbsp;</p>', NULL, NULL, 54.982559, -1.741038, 19, NULL, NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(98, 33, 'Yevgeni Zamyatin', '<p>	<strong>Yevgeni Zamyatin 1884-1937 </strong></p><p>	Eminenet Russian writer, lived here 1916-17. His early novels were based on Newcastle. His masterpice &#39;We&#39; was a major influence on Orwell&#39;s &#39;1984&#39;</p><p>	19 Saunderson Road, Jesmond<br />	&nbsp;</p><p>	<br />	&nbsp;</p>', '<p>	Yevgeni Zamyatin 1884-1937 Eminenet Russian writer, lived here 1916-17. His early novels were based on Newcastle. His masterpice &#39;We&#39; was a major influence on Orwell&#39;s &#39;1984&#39;<br />	19 Saunderson Road, Jesmond<br />	&nbsp;</p>', NULL, NULL, 54.993534, -1.604615, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3656.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(99, 34, 'William Straker', '<p>	<strong>William Straker (1855-1941) </strong></p><p>	Worked here as Northumberlands Miners&#39; Union Leader. In work, housing, health and education, he was a voice for social reform and welfare for all. A true Northumbrian.<br />	&nbsp;</p>', '<p>	William Straker (1855-1941) Worked her as Northumberlands Miners&#39; Union Leader. In work, housing, health and education, he was a voice for social reform and welfare for all. A true Northumbrian.<br />	&nbsp;</p>', NULL, NULL, 54.977108, -1.609229, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3716.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(100, 35, 'Balmbra''s', '<p>	<strong>Balmbra&#39;s</strong></p><p>	Balmbra&#39;s Site of the &quot;Wheatsheaf&quot; Public House and music room. Recuilt 1902. Named after John Balmbra, licencee in 1862 when George Ridley first performed his song &quot;The Blaydon Races&quot;<br />	&nbsp;</p>', '<p>	Balmbra&#39;s Site of the &quot;Wheatsheaf&quot; Public House and music room. Recuilt 1902. Named after John Balmbra, licencee in 1862 when George Ridley first performed his song &quot;The Blaydon Races&quot;<br />	&nbsp;</p>', NULL, NULL, 54.970818, -1.612169, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3605.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(101, 36, 'Black Gate', '<p>	<strong>The Black Gate </strong></p><p>	Principal gateway to castle built 1247-50. Upper two storeys built in the seventeenth century. Restored, notably by R.J. Johnson 1883-84<br />	&nbsp;</p>', '<p>	The Black Gate Principal gateway to castle built 1247-50. Upper two storeys built in the seventeenth century. Restored, notably by R.J. Johnson 1883-84<br />	&nbsp;</p>', NULL, NULL, 54.969353, -1.610889, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3536.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(102, 37, 'Cale Cross', '<p>	<strong>Cale Cross</strong></p><p>	This market cross where food was sold (Cale- cabbage) stood near this spot until 1807. first mentioned in 1309 it was rebuilt in 1783 to design of David Stephenson. Reerected on the grounds of Blagdon Hall.<br />	&nbsp;</p>', '<p>	Cale Cross This market cross where food was sold (Cale- cabbage) stood near this spot until 1807. first mentioned in 1309 it was rebuilt in 1783 to design of David Stephenson. Reerected on the grounds of Blagdon Hall.<br />	&nbsp;</p>', NULL, NULL, 54.969322, -1.607791, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3618.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(103, 38, 'Castle Keep', '<p>	<strong>The Castle Keep </strong></p><p>	Principal Tower of the castle built by Henry II in 1168-78. The City&#39;s name derives from the earlier castle on the site which was founded in 1080 by Robert Curthose, eldest son of William the Conquerer<br />	&nbsp;</p>', '<p>	The Castle Keep Principal Tower of the castle built by Henry II in 1168-78. The City&#39;s name derives from the earlier castle on the site which was founded in 1080 by Robert Curthose, eldest son of William the Conquerer<br />	&nbsp;</p>', NULL, NULL, 54.969067, -1.609615, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3535.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(104, 39, 'Guildhall', '<p>	<strong>The Guildhall </strong></p><p>	Present building incorporates part of Robert Trollope&#39;s town court of 1655-8. North front (1796) by William Newton and David Stephenson; south front (1809); east end (1823) by John Dobson; altered 1880. Centre of town&#39;s government until 1858.<br />	&nbsp;</p>', '<p>	The Guildhall Present building incorporates part of Robert Trollope&#39;s town court of 1655-8. North front (1796) by William Newton and David Stephenson; south front (1809); east end (1823) by John Dobson; altered 1880. Centre of town&#39;s government until 1858.<br />	&nbsp;</p>', NULL, NULL, 54.968418, -1.607445, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3621.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(105, 40, 'Hadrian''s Wall', '<p>	<strong>Hadrian&#39;s Wall </strong></p><p>	Remains of Hadrian&#39;s Wall found on this site in 1981 have been preserved below ground level with the co-operation of the North Housing Association Ltd.<br />	&nbsp;</p>', '<p>	Hadrian&#39;s Wall Remains of Hadrian&#39;s Wall found on this site in 1981 have been preserved below ground level with the co-operation of the North Housing Association Ltd.<br />	&nbsp;</p>', NULL, NULL, 54.974236, -1.596825, 21, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3707.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(106, 41, 'Mo Mowlam', '<p>	<strong>Mo Mowlam 1949-2005 </strong></p><p>	Respected Politician MP for Redcer 1987-2001 Northern Ireland secretary 1997-1999, led talks that resulted in the Good Friday Agreement in 1998. Lived in this house from 1979-1983. &quot;It takes courage to push things forward&quot;<br />	&nbsp;</p>', '<p>	Mo Mowlam 1949-2005 Respected Politician MP for Redcer 1987-2001 Northern Ireland secretary 1997-1999, led talks that resulted in the Good Friday Agreement in 1998. Lived in this house from 1979-1983. &quot;It takes courage to push things forward&quot;<br />	&nbsp;</p>', NULL, NULL, 54.970200, -1.625665, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3569.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(107, 42, 'John Gilroy', '<p>	<strong>John Gilroy 1898-1985 </strong></p><p>	Lived in this house as a boy. Royal Portrait painter, Advertising designer &amp; artist famous for the Guinness Zoo Animals &amp; World War II posters &#39;Be like Dad - Kepp Mum&#39;</p><p>	25 Kingsley &nbsp;Place<br />	&nbsp;</p>', '<p>	John Gilroy 1898-1985 Lived in this house as a boy. Royal Portrait painter, Advertising designer &amp; artist famous for the Guinness Zoo Animals &amp; World War II posters &#39;Be like Dad - Kepp Mum&#39;<br />	&nbsp;</p><p>	25 Kingsley &nbsp;Place</p>', NULL, NULL, 54.981190, -1.586897, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/John_Gilroy.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(108, 43, 'William Newton', '<p>	<strong>William Newton 1730-1798 </strong></p><p>	Eminent local architect Responsible for numerous country houses, the Assembly Rooms, St. Snn&#39;a Church &amp; Charlotte Square. He lived in this house for 28 years<br />	1 Charlotte Square</p>', '<p>	William Newton 1730-1798 Eminent local architect Responsible for numerous country houses, the Assembly Rooms, St. Snn&#39;a Church &amp; Charlotte Square. He lived in this house for 28 years<br />	1 Charlotte Square</p>', NULL, NULL, 54.971111, -1.619558, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3559.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(109, 44, 'House of Adam of Jesmond', '<p>	<strong>House of Adam of Jesmond</strong></p><p>	Built before 1267: probably abandoned by 17th century. Little known of its history. Given to Newcastle in 1879 as part of Armstrong&#39;s Park. Repairs in 1897 directed by W H Knowles, Architect.<br />	&nbsp;</p>', '<p>	Built before 1267: probably abandoned by 17th century. Little known of its history. Given to Newcastle in 1879 as part of Armstrong&#39;s Park. Repairs in 1897 directed by W H Knowles, Architect.<br />	&nbsp;</p>', NULL, NULL, 54.984978, -1.583325, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/House_of_Adam.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(110, 45, 'Lort Burn, Guildhall', '<p>	<strong>Lort Burn, Guildhall</strong></p><p>	Originally Dene Burn (dirty burn) from the later 14th century. Rising in Leazes it follows the line of Dean Street and enters the river near this spot. High Bridge and Low Bridge mark early bridges across it.<br />	&nbsp;</p>', '<p>	Originally Dene Burn (dirty burn) from the later 14th century. Rising in Leazes it follows the line of Dean Street and enters the river near this spot. High Bridge and Low Bridge mark early bridges across it.<br />	&nbsp;</p>', NULL, NULL, 54.968498, -1.607673, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3624.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(111, 46, 'Tyne and Wear County Council', '<p>	<strong>Tyne and Wear County Council</strong></p><p>	From this building the Councillors and staff of Tyne and Wear County Council loyally served the people of Tyneside and Wearside, and were their constant advocates for prosperity, safety and a better life.<br />	&nbsp;</p>', '<p>	Tyne and Wear County Council</p><p>	From this building the Councillors and staff of Tyne and Wear County Council loyally served the people of Tyneside and Wearside, and were their constant advocates for prosperity, safety and a better life.<br />	&nbsp;</p>', NULL, NULL, 54.980946, -1.605053, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3710.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(112, 47, 'Scotswood Delaval Drift', '<p>	<strong>Scotswood Delaval Drift</strong></p><p>	The drift entrance to Scotswod Delaval mine. Restored by Tyne and Wear County Council 1896<br />	&nbsp;</p>', '<p>	The drift entrance to Scotswod Delaval mine. Restored by Tyne and Wear County Council 1896<br />	&nbsp;</p>', NULL, NULL, 54.966339, -1.672642, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3702.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(113, 48, 'The Mill', '<p>	<strong>The Mill</strong></p><p>	Mabel&#39;s Mill, a water corn mill of the Ridleys existed here by 1740; from circa 1848 called Heaton Mill. A flint mill from mid to late 10th century. Acquired by Lord Armstrong in 1863.<br />	&nbsp;</p>', '<p>	The Mill</p><p>	Mabel&#39;s Mill, a water corn mill of the Ridleys existed here by 1740; from circa 1848 called Heaton Mill. A flint mill from mid to late 10th century. Acquired by Lord Armstrong in 1863.<br />	&nbsp;</p>', NULL, NULL, 54.999153, -1.601708, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3674.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(114, 49, 'Carlton Terrace - John Dobson', '<p>	<strong>John Dobson - Carlton Terrace</strong></p><p>	This large terrace was designed by Dobson in about 1840 on a road laid out by him in the 1830s.<br />	&nbsp;</p>', '<p>	John Dobson - Carlton Terrace</p><p>	This large terrace was designed by Dobson in about 1840 on a road laid out by him in the 1830s.<br />	&nbsp;</p>', NULL, NULL, 54.980869, -1.610361, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3589.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(115, 50, 'Central Station - John Dobson', '<p>	<strong>Central Station</strong></p><p>	John Dobson designed the Central Station and its train shed, which were built in 1847-50. The Portico was added in 1863 by Thomas Prosser.<br />	&nbsp;</p>', '<p>	Central Station</p><p>	John Dobson designed the Central Station and its train shed, which were built in 1847-50. The Portico was added in 1863 by Thomas Prosser.<br />	&nbsp;</p>', NULL, NULL, 54.968784, -1.617275, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3530.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(116, 51, 'Eldon Square - John Dobson', '<p>	<strong>Eldon Square</strong></p><p>	This Terrace is the only remaining side of old Eldon Square, built to Dobson&#39;s design 1835-7<br />	&nbsp;</p>', '<p>	Eldon Square</p><p>	This Terrace is the only remaining side of old Eldon Square, built to Dobson&#39;s design 1835-7<br />	&nbsp;</p>', NULL, NULL, 54.974178, -1.614540, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3510.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(117, 52, 'Grainger Market - John Dobson', '<p>	<strong>Grainger Market</strong></p><p>	This covered vegetable and butcher market, once the largest in the country, was designed by Dobson and opened in 1835<br />	&nbsp;</p>', '<p>	Grainger Market</p><p>	This covered vegetable and butcher market, once the largest in the country, was designed by Dobson and opened in 1835<br />	&nbsp;</p>', NULL, NULL, 54.973022, -1.615537, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3603.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(118, 53, 'Grey Street - John Dobson', '<p>	<strong>Grey Street</strong></p><p>	The side of the street up to Shakespeare Street was designed by John Dobson and built in 1835-37<br />	<br />	&nbsp;</p>', '<p>	Grey Street</p><p>	The side of the street up to Shakespeare Street was designed by John Dobson and built in 1835-37<br />	&nbsp;</p>', NULL, NULL, 54.971436, -1.611037, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3596.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(119, 54, 'Jesmond Parish Church - John Dobson', '<p>	<strong>Jesmond Parish Church</strong></p><p>	The Church was designed in 1858 by Dobson and was built in memory of the notable preacher Richard Clayton.<br />	&nbsp;</p>', '<p>	<strong>Jesmond Parish Church</strong></p><p>	The Church was designed in 1858 by Dobson and was built in memory of the notable preacher Richard Clayton.<br />	&nbsp;</p>', NULL, NULL, 54.982422, -1.606327, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3652.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(120, 55, 'John Dobson''s House - John Dobson', '<p>	<strong>John Dobson&#39;s 1787 - 1865 Architect</strong></p><p>	Built this house about 1823 and lived here until his death in January 1865<br />	&nbsp;</p>', '<p>	<strong>John Dobson&#39;s 1787 - 1865 Architect</strong></p><p>	Built this house about 1823 and lived here until his death in January 1865<br />	&nbsp;</p>', NULL, NULL, 54.974682, -1.608348, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3685.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(121, 56, 'Lying - in Hospital - John Dobson', '<p>	<strong>Lying - in Hosptial</strong></p><p>	Dobson designed this charitable institution for poor married pregnant women in 1825.<br />	&nbsp;</p>', '<p>	Lying - in Hospital</p><p>	Dobson designed this charitable institution for poor married pregnant women in 1825.<br />	&nbsp;</p>', NULL, NULL, 54.974407, -1.608692, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3551.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(122, 57, 'Market Keepers House/ Cattle Market Office - John Dobson', '<p>	<strong>Market Keepers House/ Cattle Market Office</strong></p><p>	John Dobson designed this market keeper&#39;s office and toll house in 1831.<br />	&nbsp;</p>', '<p>	Market Keepers House/ Cattle Market Office</p><p>	John Dobson designed this market keeper&#39;s office and toll house in 1831.<br />	&nbsp;</p>', NULL, NULL, 54.967548, -1.621336, 18, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3567.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(123, 58, 'St. Mary''s Place - John Dobson', '<p>	<strong>1 St. Mary&#39;s Place</strong></p><p>	John Dobson designed this row of houses in 1829 to complement his church of St Thomas&#39; opposite.<br />	&nbsp;</p>', '<p>	1 St. Mary&#39;s Place</p><p>	John Dobson designed this row of houses in 1829 to complement his church of St Thomas&#39; opposite.<br />	&nbsp;</p>', NULL, NULL, 54.977871, -1.611171, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3504.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(124, 59, 'St. Thomas'' Church - John Dobson', '<p>	<strong>St. Thomas&#39; Church</strong></p><p>	This church was begun in 1827 to designs by Dobson; it was his first important church.<br />	&nbsp;</p>', '<p>	St. Thomas&#39; Church</p><p>	This church was begun in 1827 to designs by Dobson; it was his first important church.<br />	&nbsp;</p>', NULL, NULL, 54.978127, -1.613102, 17, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3594.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(125, 60, 'Danish Seamen''s Club', '<p>	<strong>Danish Seamen&#39;s Club</strong></p><p>	From 1940-45 Newcastle was the official home town to 3000 Danish Sailors serving in the British Merchant Navy. The St. Nicholas buildings housed their unions, clubs and the Danish Merchant Navy Reserve Pool.<br />	&nbsp;</p>', '<p>	Danish Seamen&#39;s Club</p><p>	From 1940-45 Newcastle was the official home town to 3000 Danish Sailors serving in the British Merchant Navy. The St. Nicholas buildings housed their unions, clubs and the Danish Merchant Navy Reserve Pool.<br />	&nbsp;</p>', NULL, NULL, 54.969479, -1.615720, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/DSCN3609.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(126, 61, 'Keelman''s Hospital', '<p>	<strong>Keelman&#39;s Hospital</strong></p><p>	The fellowship of Keelmen was first mentioned in 1516. They established a charity in 1699 and began the building of the hospital in 1701.<br />	&nbsp;</p>', '<p>	Keelman&#39;s Hospital</p><p>	The fellowship of Keelmen was first mentioned in 1516. They established a charity in 1699 and began the building of the hospital in 1701.<br />	&nbsp;</p>', NULL, NULL, 54.971348, -1.601853, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3544.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(127, 62, 'Merchant''s House', '<p>	<strong>Merchant&#39;s House</strong></p><p>	The only mediaeval house and warehouse complex with a private quay to survive in Newcastle. It was separated from the river in 1985. The present building s are 16th century and later and were restored in 1982-4<br />	<br />	&nbsp;</p>', '<p>	Merchant&#39;s House</p><p>	The only mediaeval house and warehouse complex with a private quay to survive in Newcastle. It was separated from the river in 1985. The present building s are 16th century and later and were restored in 1982-4<br />	<br />	&nbsp;</p>', NULL, NULL, 54.967377, -1.610015, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3726.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(128, 63, 'Sailing Ship''s Owners', '<p>	<strong>Sailing Ship&#39;s Owners, Exchange Buildings</strong></p><p>	Throughout the age of sail, this Quayside area around the Exchange Buildings (c.1861) was home to Newcastle&#39;s ship owners, including such men as R Beckwith, H milvan and T Miller.<br />	&nbsp;</p>', '<p>	Sailing Ship&#39;s Owners, Exchange Buildings</p><p>	Throughout the age of sail, this Quayside area around the Exchange Buildings (c.1861) was home to Newcastle&#39;s ship owners, including such men as R Beckwith, H milvan and T Miller.<br />	&nbsp;</p>', NULL, NULL, 54.968887, -1.605519, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3722.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(129, 64, 'The Custom House', '<p>	<strong>The Custom House</strong></p><p>	Built in 1766 to replace the Custom House at the west end of Quayside. It was altered and refronted in 1833 by architect Sidney Smirke.<br />	&nbsp;</p>', '<p>	The Custom House</p><p>	Built in 1766 to replace the Custom House at the west end of Quayside. It was altered and refronted in 1833 by architect Sidney Smirke.<br />	&nbsp;</p>', NULL, NULL, 54.969109, -1.604723, 21, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3632.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(130, 65, 'Trinity House', '<p>	<strong>Trinity House</strong></p><p>	This site was acquired in 1505 by the Fellowship of Masters and Mariners of Ships of the town of Newcastle upon Tyne. The present buildings date from the 16th to 19th centuries.<br />	&nbsp;</p>', '<p>	Trinity House</p><p>	This site was acquired in 1505 by the Fellowship of Masters and Mariners of Ships of the town of Newcastle upon Tyne. The present buildings date from the 16th to 19th centuries.<br />	&nbsp;</p>', NULL, NULL, 54.970139, -1.605152, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3634.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(131, 66, 'All Saints Church', '<p>	<strong>All Saints Church</strong></p><p>	This rare elliptical building of 1786-89 (spire 1796) replaced the decaying mediaeval Church of All Hallows. Designed by architect, David Stephenson, of Newcastle (1757-1819). It closed as a church in 1961 and has since undergone major restoration.<br />	&nbsp;</p>', '<p>	All Saints Church</p><p>	This rare elliptical building of 1786-89 (spire 1796) replaced the decaying mediaeval Church of All Hallows. Designed by architect, David Stephenson, of Newcastle (1757-1819). It closed as a church in 1961 and has since undergone major restoration.<br />	&nbsp;</p>', NULL, NULL, 54.969959, -1.606877, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3720.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(132, 67, 'Jesmond Cemetery Gates', '<p>	<strong>Jesmond Cemetery Gates</strong></p><p>	The Gateway and former Chapels were built for the newcastle General Cemetery Company in 1836 by architect John Dobson. They were restored by the County Council in 1978.<br />	&nbsp;</p>', '<p>	Jesmond Cemetery Gates</p><p>	The Gateway and former Chapels were built for the newcastle General Cemetery Company in 1836 by architect John Dobson. They were restored by the County Council in 1978.<br />	&nbsp;</p>', NULL, NULL, 54.984009, -1.599970, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3712.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(133, 68, 'St. Anne''s Church', '<p>	<strong>St. Anne&#39;s Church</strong></p><p>	Built in 1768 to designs by William Newton, a Newcastle architect. Set in open fields outside the Town Walls, it replaced an ancient Chapel of Ease to the Church of All Saints.<br />	&nbsp;</p>', '<p>	St. Anne&#39;s Church</p><p>	Built in 1768 to designs by William Newton, a Newcastle architect. Set in open fields outside the Town Walls, it replaced an ancient Chapel of Ease to the Church of All Saints.<br />	&nbsp;</p>', NULL, NULL, 54.972397, -1.594702, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3542.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(134, 69, 'St. Mary''s Chapel', '<p>	<strong>St. Mary&#39;s Chapel </strong></p><p>	Built in the 12h century and enlarged in the 14th. It was a place of pilgrimage in the Mediaeval period and was sold by Edward VI to Newcastle in 1549. After having many owners, it was returned to Newcastle by Lord Armstrong in 1883<br />	&nbsp;</p>', '<p>	St. Mary&#39;s Chapel</p><p>	Built in the 12h century and enlarged in the 14th. It was a place of pilgrimage in the Mediaeval period and was sold by Edward VI to Newcastle in 1549. After having many owners, it was returned to Newcastle by Lord Armstrong in 1883<br />	&nbsp;</p>', NULL, NULL, 54.992554, -1.596011, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3658.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(135, 70, 'St. Mary''s Well', '<p>	<strong>St. Mary&#39;s Well</strong></p><p>	This is traditionally considered to be an ancient holy well, but is probably no earler than the late 17th century. William Coulson built a bathing place beside it in the early 18th century. It was remodelled in the 19th century.<br />	&nbsp;</p>', '<p>	St. Mary&#39;s Well</p><p>	This is traditionally considered to be an ancient holy well, but is probably no earler than the late 17th century. William Coulson built a bathing place beside it in the early 18th century. It was remodelled in the 19th century.<br />	&nbsp;</p>', NULL, NULL, 54.992283, -1.595835, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3660.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(136, 71, 'St. Thomas'' Chapel', '<p>	<strong>St. Thomas&#39; Chapel</strong></p><p>	Chapel of St Thomas the Martyr (Archbishop Thomas Becket, died 1170) stood on Old Tyne Bridge near this spot until 1830 when it was replaced by St Thomas&#39; Church in Barras Bridge.<br />	&nbsp;</p>', '<p>	St. Thomas&#39; Chapel</p><p>	Chapel of St Thomas the Martyr (Archbishop Thomas Becket, died 1170) stood on Old Tyne Bridge near this spot until 1830 when it was replaced by St Thomas&#39; Church in Barras Bridge.<br />	&nbsp;</p>', NULL, NULL, 54.968231, -1.608215, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3629.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(137, 72, 'Wesley Orphan House/ John Wesley', '<p>	<strong>Wesley Orphan House/ John Wesley</strong></p><p>	John Wesley erected on this site in 1783 &quot;The Orphan House&quot; which was also the headquarters of Methodism in the North<br />	&nbsp;</p>', '<p>	Wesley Orphan House/ John Wesley</p><p>	John Wesley erected on this site in 1783 &quot;The Orphan House&quot; which was also the headquarters of Methodism in the North<br />	&nbsp;</p>', NULL, NULL, 54.976566, -1.613240, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3718.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(138, 73, 'West Farm, Black Callerton - Stephensons', '<p>	<strong>West Farm, Black Callerton</strong></p><p>	Stephenson worked at the nearby Dolly Pit from 1801-1802 when he married Frances Henderson (1769-1806), mother of Robert. In 1820 he married Elizabeth hindmarsh a Black Callerton farmer&#39;s daughter.<br />	&nbsp;</p>', '<p>	West Farm, Black Callerton</p><p>	Stephenson worked at the nearby Dolly Pit from 1801-1802 when he married Frances Henderson (1769-1806), mother of Robert. In 1820 he married Elizabeth hindmarsh a Black Callerton farmer&#39;s daughter.<br />	&nbsp;</p>', NULL, NULL, 55.022385, -1.729942, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3689.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(139, 74, 'High Level Bridge - Stephensons', '<p>	<strong>High Level Bridge</strong></p><p>	The original lighting columns on the High Level Bridge were re-furbished and brought back into service by Network Rail in 2008 with funding contributions from: The Railway Heritage Trust, Gateshead Metropolitan Borough Council and Newcastle City Council.<br />	&nbsp;</p>', '<p>	The original lighting columns on the High Level Bridge were re-furbished and brought back into service by Network Rail in 2008 with funding contributions from: The Railway Heritage Trust, Gateshead Metropolitan Borough Council and Newcastle City Council.<br />	&nbsp;</p>', NULL, NULL, 54.967030, -1.608531, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3534.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(140, 75, 'Literary and Philosophical Society - Stephensons', '<p>	<strong>Literary and Philosophical Society</strong><br />	Society established 1793. This building, designed by John Green, opened in 1825. Robert Stephenson was President of the Society, 1855-59.<br />	&nbsp;</p>', '<p>	Literary and Philosophical Society<br />	Society established 1793. This building, designed by John Green, opened in 1825. Robert Stephenson was President of the Society, 1855-59.<br />	&nbsp;</p>', NULL, NULL, 54.969383, -1.613885, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3584.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(141, 76, 'Newburn Parish Church - Stephenson ', '<p>	<strong>Newburn Parish Church</strong></p><p>	George Stephenson, enginewright, locomotive pioneer and railway promoter married Frances Henderson on 28th November 1802 and secondly Elizabeth Hindmarsh on 29th March 1820 in this church.<br />	&nbsp;</p>', '<p>	Newburn Parish Church</p><p>	George Stephenson, enginewright, locomotive pioneer and railway promoter married Frances Henderson on 28th November 1802 and secondly Elizabeth Hindmarsh on 29th March 1820 in this church.<br />	&nbsp;</p>', NULL, NULL, 54.982552, -1.741159, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3694.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(142, 77, 'Robert Stephenson''s House - Stephensons', '<p>	<strong>Robert Stephenson&#39;s House</strong></p><p>	Robert Stephenson Engineer lived here from his marriage in 1829 until he removed to London in 1833. During this time he designed and constructed the &#39;Rocket&#39; and later the &#39;Planet&#39;, the prototype for more than a century of steam locomotive development.<br />	&nbsp;</p>', '<p>	Robert Stephenson Engineer lived here from his marriage in 1829 until he removed to London in 1833. During this time he designed and constructed the &#39;Rocket&#39; and later the &#39;Planet&#39;, the prototype for more than a century of steam locomotive development.<br />	&nbsp;</p>', NULL, NULL, 54.970947, -1.626355, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3574.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ncl_plaques` (`uid`, `trail_point`, `title`, `short_text`, `full_text`, `video_embed_url`, `audio`, `lat`, `lng`, `zoom`, `image`, `full_link`, `trail`, `pointtype`, `divposition`, `divleft`, `divright`, `divxindex`, `postop`, `posleft`) VALUES
(143, 78, 'Stephenson Works - Stephensons', '<p>	<strong>Stephenson Works</strong></p><p>	Robert Stephenson &amp; Company established in 1823 the world&#39;s first purpose built locomotive factory. &#39;Locomotion No. 1&#39; was designed and constructed in 1828, &#39;Rocket&#39; in 1829 and &#39;Planet&#39; in 1830.<br />	&nbsp;</p>', '<p>	Robert Stephenson &amp; Company established in 1823 the world&#39;s first purpose built locomotive factory. &#39;Locomotion No. 1&#39; was designed and constructed in 1828, &#39;Rocket&#39; in 1829 and &#39;Planet&#39; in 1830.<br />	&nbsp;</p>', NULL, NULL, 54.967175, -1.615006, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3705.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(144, 79, 'Water Row - Stephensons', '<p>	<strong>Water Row, Newburn</strong><br />	From 1798-1801 George Stephenson was in charge of Robert Hawthorn&#39;s new pumping engine at Water Row Pit, where George&#39;s father, Robert was a fireman.<br />	&nbsp;</p>', '<p>	Water Row, Newburn<br />	From 1798-1801 George Stephenson was in charge of Robert Hawthorn&#39;s new pumping engine at Water Row Pit, where George&#39;s father, Robert was a fireman.<br />	<br />	&nbsp;</p>', NULL, NULL, 54.981651, -1.744241, 17, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3697.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(145, 80, 'Durham Tower - Town Wall', '<p>	<strong>Durham Tower</strong></p><p>	The Durham Tower, built in the late 13th century<br />	&nbsp;</p>', '<p>	The Durham Tower, built in the late 13th century<br />	&nbsp;</p>', NULL, NULL, 54.971149, -1.620677, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3520.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(146, 81, 'Gunner Tower - Town Wall', '<p>	<strong>Gunner Tower</strong></p><p>	Site of the late 13th century Gunner Tower which was converted 1821 for use by the Company of Slaters and Tylers. It was Demolished in 1885 and the foundations were excavated in 1964.<br />	&nbsp;</p>', '<p>	Gunner Tower</p><p>	Siteof the late 13th century Gunner Tower which was converted 1821 for use by the Company of Slaters and Tylers. It was Demolished in 1885 and the foundations were excavated in 1964.<br />	&nbsp;</p>', NULL, NULL, 54.969368, -1.618272, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3527.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(147, 82, 'The Plummer Tower - Town Wall', '<p>	<strong>The Plummer Tower, </strong></p><p>	built in the late 13th century, was granted to the Company of Masons in 1742, who partly rebuilt it. It is the only surviving two storey tower.<br />	&nbsp;</p>', '<p>	The Plummer Tower, built in the late 13th century, was granted to the Company of Masons in 1742, who partly rebuilt it. It is the only surviving two storey tower.</p>', NULL, NULL, 54.973812, -1.607928, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3550.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(148, 83, 'The Herber Tower - Town Wall', '<p>	<strong>The Herber Tower</strong>,</p><p>	which was built in the 13th century, was restored in 1770-1 by the company of Armourers, Curriers and Feltmakers who used the Tower for a meeting hall.<br />	&nbsp;</p>', '<p>	The Herber Tower, which was built in the 13th century, was restored in 1770-1 by the company of Armourers, Curriers and Feltmakers who used the Tower for a meeting hall.<br />	&nbsp;</p>', NULL, NULL, 54.973267, -1.619729, 21, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3519.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(149, 84, 'The Sallyport Tower - Town Wall', '<p>	<strong>The Sallyport or Wall Knoll Tower</strong>,</p><p>	a lesser gateway, was buitl in the early 14th century. The Company of Ships Carpenters rebuilt the upper storey in 1716 as a meeting hall.<br />	&nbsp;</p>', '<p>	The Sallyport or Wall Knoll Tower, a lesser gateway, was buitl in the early 14th century. The Company of Ships Carpenters rebuilt the upper storey in 1716 as a meeting hall.<br />	&nbsp;</p>', NULL, NULL, 54.971340, -1.603537, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3547.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(150, 85, 'Sand Gate - Town Wall', '<p>	<strong>Sand Gate</strong></p><p>	This wall stands on the line of the mediaeval town wall constructed in the 14th century and demolished by order of the Town Council in 1763.<br />	&nbsp;</p>', '<p>	This wall stands on the line of the mediaeval town wall constructed in the 14th century and demolished by order of the Town Council in 1763.<br />	&nbsp;</p>', NULL, NULL, 54.970394, -1.600018, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3636.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(151, 86, 'Postern Gate - Town Wall', '<p>	<strong>Postern gate</strong></p><p>	In 1280, the Black Friars were granted the right to make this postern through the City Wall to give them access to their gardens beyond<br />	&nbsp;</p>', '<p>	In 1280, the Black Friars were granted the right to make this postern through the City Wall to give them access to their gardens beyond<br />	&nbsp;</p>', NULL, NULL, 54.972343, -1.620540, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3522.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(152, 87, 'Morden Tower - Town Wall', '<p>	<strong>The Morden Tower</strong>,</p><p>	built in the late 13th century, was used by the Company of Glaziers, Plumbers, Pewters and Painters from 1619. It was Partly rebuilt in 1700.<br />	&nbsp;</p>', '<p>	The Morden Tower, built in the late 13th century, was used by the Company of Glaziers, Plumbers, Pewters and Painters from 1619. It was Partly rebuilt in 1700.<br />	&nbsp;</p>', NULL, NULL, 54.972984, -1.619960, 21, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3524.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(153, 88, 'Andrew''s Tower - Town Wall', '<p>	<strong>Andrew&#39;s Tower</strong></p><p>	In 1810 part of the Wall was removed to allow access from Darn Crook to Gallowgate. The Andrew Tower, to the north of here, was lost when the churchyard was enlarged in 1818<br />	&nbsp;</p>', '<p>	Andrew&#39;s Tower</p><p>	In 1810 part of the Wall was removed to allow access from Darn Crook to Gallowgate. The Andrew Tower, to the north of here, was lost when the churchyard was enlarged in 1818<br />	&nbsp;</p>', NULL, NULL, 54.973625, -1.618997, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3513.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(154, 89, 'Hanover Street - Town Wall', '<p>	<strong>Town Wall</strong></p><p>	This stretch of wall was built in the early 14th century. From here the wall wakl stepped down to the Close Gate at the foot of the slope and came to be known as the Breakneck stairs</p>', '<p>	<strong><strong>Town Wall</strong></strong></p><p>	This stretch of wall was built in the early 14th century. From here the wall wakl stepped down to the Close Gate at the foot of the slope and came to be known as the Breakneck stairs</p>', NULL, NULL, 54.967113, -1.613519, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3532.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(155, 90, 'Ever Tower - Town Wall', '<p>	<strong>Ever Tower</strong></p><p>	Remains of the late 13th century Ever Tower used by company of Paviors, Colliers and Carriagemen during the 19th century largely demolished 1908-10</p>', '<p>	Ever Tower</p><p>	Remains of the late 13th century Ever Tower used by company of Paviors, Colliers and Carriagemen during the 19th century largely demolished 1908-10</p>', NULL, NULL, 54.972561, -1.620395, 19, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3517.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(156, 91, 'Corner Tower - Town Wall', '<p>	<strong>Corner Tower</strong></p><p>	Two turrets at right angles to one another. At this point, in the early 14th century, the wall was turned east to enclose the newly aquired suburb of Pandon</p>', '<p>	Corner Tower</p><p>	Two turrets at right angles to one another. At this point, in the early 14th century, the wall was turned east to enclose the newly aquired suburb of Pandon</p>', NULL, NULL, 54.971340, -1.606218, 20, 'http://exploreheritage.co.uk/media/images/nccplaques/DSCN3540.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(157, 92, 'Thomas Spence', '<p>	<strong>Thomas Spence, 1750 &ndash; 1814 </strong></p><p>	Born Quayside, Newcastle. Utopian writer and land reformer. Courageous, pioneering campaigner for the rights of men and women. Founded a schoolroom and debating society in Broad Garth. &ldquo;Dare to be free&rdquo;</p>', '<p>	<strong>Thomas Spence, 1750 &ndash; 1814 </strong></p><p>	Born Quayside, Newcastle. Utopian writer and land reformer. Courageous, pioneering campaigner for the rights of men and women. Founded a schoolroom and debating society in Broad Garth. &ldquo;Dare to be free&rdquo;</p>', NULL, NULL, 54.969002, -1.605136, 18, 'http://exploreheritage.co.uk/media/images/nccplaques/100620A_025-web.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(158, 93, 'Dame Allan''s Schools', '<p>	<strong>College Street</strong></p><p>	<strong>Dame Allan&#39;s Schools 1883 - 1935</strong></p><p>	Dame Allan&#39;s Boys&#39; School (first floor) and Girls&#39; School (ground floor) by R J Johnson.</p><p>	Dame Eleanor Allan founded the original schools in 1703 to provide a proper education for 40 poor boys and 20 poor girls of the parishes of St Nicholas and St John.</p>', '<p>	<strong>College Street</strong></p><p>	<strong>Dame Allan&#39;s Schools 1883 - 1935</strong></p><p>	Dame Allan&#39;s Boys&#39; School (first floor) and Girls&#39; School (ground floor) by R J Johnson.</p><p>	Dame Eleanor Allan founded the original schools in 1703 to provide a proper education for 40 poor boys and 20 poor girls of the parishes of St Nicholas and St John.</p>', NULL, NULL, 54.977417, -1.609803, 19, 'http://www.exploreheritage.co.uk/media/images/nccplaques/101101B_018_web.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(159, 94, 'Lord Armstrong', '<p>	<strong>High Bridge</strong></p><p>	<strong>Lord Armstrong, 1810 - 1900</strong></p><p>	William George Armstrong&#39;s water-powered rotary engine was built here at Henry Watson&#39;s works, 1838.</p><p>	Inventor, engineer, scientist and businessman, Armstrong employed 25,000 people at his Elswick works.</p>', '<p>	<strong>High Bridge</strong></p><p>	<strong>Lord Armstrong, 1810 - 1900</strong></p><p>	William George Armstrong&#39;s water-powered rotary engine was built here at Henry Watson&#39;s works, 1838.</p><p>	Inventor, engineer, scientist and businessman, Armstrong employed 25,000 people at his Elswick works.</p>', NULL, NULL, 54.971893, -1.612570, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/101126C_011_web.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(190, 95, 'Muriel Robb', '<p>	<strong>102 Osborne Road. Jesmond Lawn Tennis Club</strong></p><p>	Muriel Robb, 1878 - 1907.</p><p>	Wimbledon Ladies&#39; Singles Champion 1902.</p><p>	Played at Jesmond Lawn Tennis Club.</p><p>	Holds unique record for winning the England, Scotland, Wales and Ireland titles in 1902.</p>', '<p>	<strong>102 Osborne Road. Jesmond Lawn Tennis Club</strong></p><p>	Muriel Robb, 1878 - 1907.</p><p>	Wimbledon Ladies&#39; Singles Champion 1902.</p><p>	Played at Jesmond Lawn Tennis Club.</p><p>	Holds unique record for winning the England, Scotland, Wales and Ireland titles in 1902.</p>', NULL, NULL, 54.993279, -1.603004, 21, 'http://www.exploreheritage.co.uk/media/images/nccplaques/110614D_044.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL),
(191, 96, 'Milecastle on Westgate Road', '<p>	<strong>Westgate Road</strong></p><p>	<strong>A Hadrian&#39;s Wall Milecastle</strong></p><p>	2nd century A.D.</p><p>	In 1985 the south west corner of&nbsp; a milecastle (fortified gate) was discovered here. It formed part of the Roman frontier fortifications of Hadrian&#39;s Wall.</p>', '<p>	<strong>Westgate Road</strong></p><p>	<strong>A Hadrian&#39;s Wall Milecastle</strong></p><p>	2nd century A.D.</p><p>	In 1985 the south west corner of&nbsp; a milecastle (fortified gate) was discovered here. It formed part of the Roman frontier fortifications of Hadrian&#39;s Wall.</p>', NULL, NULL, 54.970131, -1.618208, 20, 'http://www.exploreheritage.co.uk/media/images/nccplaques/110929C_021.jpg', NULL, 5, 'blue', NULL, NULL, NULL, NULL, NULL, NULL);
